// <auto-generated />
namespace TraballhoDM106.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class campos_produto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(campos_produto));
        
        string IMigrationMetadata.Id
        {
            get { return "201708230315597_campos_produto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
