// <auto-generated />
namespace TraballhoDM106.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alteracao_campos_nome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteracao_campos_nome));
        
        string IMigrationMetadata.Id
        {
            get { return "201708220050526_alteracao_campos_nome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
